### ISSUE TITLE
0.91.0b3 has killed this component.

### ISSUE THREAD

**Issue by DavidFW1960** [exxamalte/home-assistant-customisations#1]
Validation error saying that  nsw_rural_fire_service_fire_danger - platform not found
Was working fine with 0.90.2

I have the latest with the new structure... /custom_components/nsw_rural_fire_service_fire_danger
and a sensor.py and ```__init__.py```

I don't know why it's broken..

**Comment by exxamalte** [comment]
Is this the error message you're getting?

`Unable to find platform nsw_rural_fire_service_fire_danger. Search path was limited to path of component: custom_components`

If so, then commit https://github.com/exxamalte/home-assistant-customisations/commit/59642390ec40db5eb47858efc0d96bf9bba9e773 should fix this.

**Comment by DavidFW1960** [comment]
Yes that was it and it's working again now. Thanks.
