### ISSUE TITLE
0.92.x changes

### ISSUE THREAD

**Issue by DavidFW1960** [exxamalte/home-assistant-customisations#2]
I got an error with 0.92.0b0 This may have been fixed in b1 but the DOMAIN needs to be specified in ```__init__.py```

Here is my new file that works:
```
# NSW Rural Fire Service - Fire Danger.
DOMAIN = "nsw_rural_fire_service_fire_danger"
```

I tried to make a PR but couldn't

**Comment by exxamalte** [comment]
OK, I can reproduce this in Home Assistant 0.92.0b0, and get the following error message.

```
AttributeError: module 'custom_components.nsw_rural_fire_service_fire_danger' has no attribute 'DOMAIN'
```

This issue does not appear anymore in Home Assistant 0.92.0b1.

There is another option to fix this - I have supplied a `manifest.json` file yesterday which also defines the domain:
https://raw.githubusercontent.com/exxamalte/home-assistant-customisations/master/nsw-rural-fire-service-fire-danger/config/custom_components/nsw_rural_fire_service_fire_danger/manifest.json

**Comment by DavidFW1960** [comment]
Ha! I only logged this issue today after changing the init file yesterday. Just d/l your changed files now.

Working fine! Thanks.

**Comment by DavidFW1960** [comment]
oh... b1 they fixed these so there is a default domain too but providing a manifest seems the best way forward.
