### ISSUE TITLE
NoneType' object has no attribute 'state

### ISSUE THREAD

**Issue by geeneo** [exxamalte/home-assistant-customisations#7]
Hi

I get the following error, hope you can help.

homeassistant.components.automation.check_pool_pump_periodically] Check Pool Pump Periodically: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object has no attribute 'state'

**Comment by exxamalte** [comment]
That error indicates that an entity is not correctly defined, and hence its state cannot be read. Did you set you set up all entities as described and used the correct names in the final [`pool_pump` configuration](https://github.com/exxamalte/home-assistant-customisations/tree/master/pool-pump#pool-pump-configuration)?

**Comment by exxamalte** [comment]
Assuming this is resolved.
