### ISSUE TITLE
Component pool_pump Integration 'pool_pump' not found.

### ISSUE THREAD

**Issue by fabiofare** [exxamalte/home-assistant-customisations#8]
Hello, I have this issue and I really can't figure out what's wrong... I alsi tried the HACS component and I had same result.

here the portion of the HA Core Log

```
2021-06-17 14:09:58 ERROR (MainThread) [homeassistant.components.hassio] The system cannot restart because the configuration is not valid: Package swimmingpool setup failed. Component pool_pump Integration 'pool_pump' not found.
2021-06-17 14:09:58 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 76, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/api/__init__.py", line 376, in post
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 518, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Package swimmingpool setup failed. Component pool_pump Integration 'pool_pump' not found.
```

**Comment by exxamalte** [comment]
It seems that the message in the title does not match the message in the log extract:
* Component pool_pump Integration 'pool_pump' not found
* Component pool_pump_service Integration 'pool_pump_service' not found.

The custom component in this git repository is called `pool_pump`. In a very early version it was called `pool_pump_service`.

To be honest I have never seen that error message before, but it sounds as if the custom component was not installed correctly. Have you manually added the files from my git repository and added all the configuration items as documented?

And which HACS component have you tried?

**Comment by fabiofare** [comment]
Thank you @exxamalte for your quick reply, the title does not match the message in the logs because is indeed my copy and paste mistake (sorry) - I edited the log in the original message.

I confirm that I've manually added the files from your git repository `pool_pump` folder and configured all as per instructions.

here the dedicated package: https://pastebin.com/U4fxKJnd
here the lines added to the main configuration file: https://pastebin.com/hqd9Dhz5

I there any assumption you are doing (like any other HA component to enable/add) but not posted on the configuration instructions?

the HACS integration I am referring is this one:  https://github.com/oncleben31/ha-pool_pump

If I remove from configuration all the references to `pool_pump` service, HA is restarting without issues.

**Comment by exxamalte** [comment]
Thanks for the details.
This custom component does not have any external dependencies and only uses some Home Assistant core components which are automatically loaded.

Now I remember that HACS repository. This should actully take care of ensuring that all files are deployed where they are needed. I assume that you are aware that there is a version number missing in the HACS repository's `manifest.json`? Without that version number the component will not be loaded anymore.

I was just trying to understand that key error message you experience:
`Package swimmingpool setup failed. Component pool_pump Integration 'pool_pump' not found.`
This indicates that you must have set up a package called `swimmingpool` which contains the relevant configuration?

I just tried to produce the same error message and can do that by just adding some invalid component name into a package file, but it does not prevent my Home Assistant instance to start up. I see the error message, but it just continues with the start-up.

Just to confirm:
Inside your config folder (where `configuration.yaml` is located) you have a folder `custom_components` -> `pool_pump` where the files `__init__.py`, `services.yaml` and `manifest.json` are located?

**Comment by fabiofare** [comment]
@exxamalte 
I get rid of HACS component (no reply to my issue.. so...) and I am using your original :)

Q1: you must have set up a package called `swimmingpool`
A1: yes. I am having this approach for all the integrations I have

Q2: file locations
A2: here the file paths 
```
• config/configuration.yaml 
• config/packages/swimmingpool.yaml
• config/custom_components/pool_pump
   |--  __init__.py
   |--  services.yaml
   |--  manifest.json 
```

FYI I have other custom components like: smarter, alexa_media, hacs... all working as expected.

**Comment by fabiofare** [comment]
@exxamalte 

I changed the following line of the file
/config/custom_components/pool_pump/manifest.json

`"version": "1"` into `"version": "1.0"`

and it worked!

**Comment by exxamalte** [comment]
That's great to see it's working for you now. I was already running out of ideas here.

Strange thing though is that `"version": "1"` works fine for me - both in my production system (core-2021.6.5) as well as my dev system (core-2021.7.0.dev0).

Just for the record could you please post the Home Assistant version you are using at the moment?

**Comment by fabiofare** [comment]
My version is:

core-2021.6.5
supervisor-2021.06.3
Home Assistant OS 6.0
